// USER ACTIONS
export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";

export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const UPDATE_PROFILE = "UPDATE_PROFILE";

// ERROR ACTIONS
export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

// POSTS ACTIONS
export const GET_POSTS = "GET_POSTS";
export const POSTS_LOADING = "POSTS_LOADING";

export const GET_POST = "GET_POST";
export const ADD_POST = "ADD_POST";
export const DELETE_POST = "DELETE_POST";
export const POST_LOADING = "POST_LOADING";
export const LIKE_POST = "LIKE_POST";

// CATEGORY ACTIONS
export const GET_CATEGORIES = "GET_CATEGORIES";
export const ADD_POINTS = "ADD_POINTS";
export const RESET_POINTS = "RESET_POINTS";

// COMMENT ACTIONS
export const GET_COMMENTS = "GET_COMMENTS";
export const ADD_COMMENT = "ADD_COMMENT";
